name: Itopya Fiyat Avcısı
on:
  schedule:
    - cron: '0 * * * *' # Her saatin başında (12:00, 13:00 vb.) çalıştır
  workflow_dispatch: # İstediğin an manuel başlatabilmen için buton ekler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Gerekli Kütüphaneleri ve Sanal Ekranı (Xvfb) Kur
        run: |
          pip install undetected-chromedriver selenium requests
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Botu Sanal Ekranda Çalıştır
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python scraper.py